spring.application.name=order-service
spring.config.import=configserver:http://localhost:8888

spring.profiles.active=dev

#qp42Q9_Z94ANAZhl4a*g

#eyJ2ZXIiOiI4LjE0LjAiLCJhZHIiOlsiMTkyLjE2OC4yLjY1OjkyMDAiXSwiZmdyIjoiMjVhZTM2OGE3MDNmZGVlYjI5YmUyZmQ3MjUxYzRhMjMzMGU4N2Q5NzU0ZWQwMTE4NTg4ODQ2ZmIwYWVlNjc4MyIsImtleSI6IkFkTDRycUFCbjNzZjI0UE1PYUlDOnhUZzZURFdTV1FvZWdIVGYzU2hMLXcifQ==