spring.application.name=module2MVC
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:C:/Users/harsh/Documents/springBootTutorials/db
spring.datasource.username=harshitDB
spring.datasource.password=harshit123
spring.jpa.hibernate.ddl-auto=update